### ISSUE TITLE
Proposition: Brute force the Inmate number

### ISSUE THREAD

**Issue by southkid23** [isome01/Intelbroker#1]
If we are going to be using the scraper to collect all the records that jail systems have, then the easiest, most practical way would be to brute force search all the possible records in a web-based jail inmate search.

Pros:
- Simple algorithm to incorporate for web-based search engine.
- Most, if not all, jail system searches have a way to search by some kind of inmate number.
- Would take shorter to brute force search than using name, dob, case number, etc

Cons:
- Too easy
- _Insert other cons here_

**Comment by isome01** [comment]
Indeed the ideal approach -> if I may, however

Pros:
 - search by name starting a, ab, abc brute force is practical for EVERY government website even as of right now. 
 - the practical way for the most general and reliable approach

Cons: 
 - If we ever use inmate number we won't know when it will end as A-Z would outweigh to be a more a practical approach.
 (Other than that, nada.)

NOTE: Like we discussed, there may be some templates we have to create for certain websites.

**Comment by southkid23** [comment]
I will have to kindly disagree with most of your points.

_**search by name starting a, ab, abc brute force is practical for EVERY government website even as of right now**_
**_the practical way for the most general and reliable approach_**

It is true that every government website will most likely have names as a search field, and upon extensive research on jail search websites (I looked at 3 or 4), there was one where an inmate number could not be used (boo hoo D': ).

However, I would not say it is practical since I think there would be a few of scenarios that we would have to account for if we wanted to guarantee (can this be guaranteed?) getting the records for every inmate.
Below are some scenarios:
- What's the minimum length of a name?
- What's the maximum length of a name?
- Should we account for names with international characters like 陳大文 or Österreicher?
- What kind of other special characters can a name have (e.g. apostrophe, comma, etc)
- Emojis?? (JK, if any county did this, I'll quit my job, do everything I can do get hired by them, and drop their tables)

While most of these questions can have clear answers, keep in mind that many more questions will when we decide to optimize the algorithm for name search because inherently, a bare brute force name search will have like 95% invalid names.


**_If we ever use inmate number we won't know when it will end as A-Z would outweigh to be a more a practical approach.
(Other than that, nada.)_**

When it comes to using an inmate's number, government sites actually seem to have a fixed set of integers ranging between 6 and 12 out of all the ones I've seen (again, not many).

Let's assume a very basic form of brute force search by name from what we know of names.
- min: 1
- max: 12 (I think people usually go with 32 but let's cut this some slack)
- chars: A-Za-z (52 since I think lowercase and uppercase should be included)
- only search by last name (some sites require last and first but again we're going for basic)

Here is a calculation I made based on the above assumptions although it is clearly wrong since I'm not taking into account the varying length of the name.

12^52 = 90,877,006,486,250,192,896   possible name combinations

Now how many of them would actually be names? What if we included other special characters? In just this basic form for brute force search by name, we can see how much time and resources will be wasted when the scraper is going through all of this.

Let's assume a basic form of brute force search by inmate number from what we know is used by the government sites:
- fixed digits max: 12
- numbers: 0-9 (10)

12^10 = 61,917,364,224  possible number combinations

Still quite a bit but a lot less than name search and at least the boundaries for the inmate number search can more or less easily optimized since these would most likely be auto-generated numbers and they usually would follow some kind of guidelines.

Also, there's not really a number you can say would never be a number used other than 000000000000. Even 000000000001 seems like a plausible number that would be used by the system (it's not though).



**Other limitations to inmate**: Most likely will not be able to use this for other type of searches like when looking for people that only have misdemeanors and felonies but have not actually been to jail. Although I suppose we can still search by case, court numbers, idk.



Just food for thought though because I think eventually, we would have to implement a scraper by name anyways.

**Comment by isome01** [comment]
To address searching by the inmate number, as for when I looked a few years ago, I supposed there wasn't much to do with it, as search by name was usually the take for MOST websites. I will agree that there will be times where inmate number search will only be used or, because depending on how they decide to index the website's profiles, inmate number search would be optimal.

These are 5 random websites I searched up that happen to offer *search by name*:
 - https://jailroster.hennepin.us/JailRosterOnline/jail-roster
 - https://inmatelocatorext.co.sherburne.mn.us/inmatelocator/
 - https://www.mississippicountysheriffar.org/roster.php
 - http://www.usacountyrecords.com/state/mississippi/jails/chickasaw-county-ms-jail-inmates/
 - https://districtofcolumbia.staterecords.org/inmate

To my surprise, actually, they don't even do inmate number. I do think your calculations on how choosing a number would be most efficient as 12^10 is obviously a better settle than worst case character search 12^52(+). 

While I think you're right about the amount of combinations in extricating the process of grabbing info by number, we also have to realize that it will vary in most cases.
 - Some websites will have at least search by name or any other extraneous info,
 - Search by name will only be available
 - Search by inmate will only be available

So let me correct myself. I don't think we can always compare the two searches as they might serve to be individually required and not so optional.

I think we should definitely implement them both. Let me know how you feel about that. I say both because the purpose of the Omni scraper is to reach all records accordingly, and it would be nice to have that option if what I said in the above holds true.
